apiVersion: apps/v1
kind: Deployment
metadata:
  name: evolution-api
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/by2-studio/evolution-api:40c30e5e820e925cf98faa90406c1ea1090d0e04
          envFrom:
            - secretRef:
                name: evolution-api-secrets
      containers:
        - name: api
          image: ghcr.io/by2-studio/evolution-api:40c30e5e820e925cf98faa90406c1ea1090d0e04
          envFrom:
            - secretRef:
                name: evolution-api-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
