apiVersion: apps/v1
kind: Deployment
metadata:
  name: evolution-api
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/by2-studio/evolution-api:3fca66ef8c2e0d7da30618818bc2976d0ba8c348
          envFrom:
            - secretRef:
                name: evolution-api-secrets
      containers:
        - name: api
          image: ghcr.io/by2-studio/evolution-api:3fca66ef8c2e0d7da30618818bc2976d0ba8c348
          envFrom:
            - secretRef:
                name: evolution-api-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
