apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evolution-api-instances
  labels:
    app.kubernetes.io/name: evolution-api
    app.kubernetes.io/part-of: evolution-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
